stages:
  - lint
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHON_VERSION: "3.10"

cache:
  paths:
    - .cache/pip

before_script:
  - python3 -m pip install --upgrade pip
  - pip install -e .

lint:
  stage: lint
  image: python:${PYTHON_VERSION}
  script:
    - pip install ruff
    - ruff check src/ tests/

test:
  stage: test
  image: python:${PYTHON_VERSION}
  script:
    - pip install pytest pytest-cov
    - pytest --cov=ozone_model --cov-report=xml
  artifacts:
    paths:
      - coverage.xml
    when: always

# codecov:
#   stage: test
#   image: python:${PYTHON_VERSION}
#   script:
#     - curl -Os https://uploader.codecov.io/latest/linux/codecov
#     - chmod +x codecov
#     - ./codecov -t ${CODECOV_TOKEN} -f coverage.xml
#   needs: [test]